# Site settings
title: Tom Mault
email: thomas@tmault.co.uk
author: Tom Mault
description: "Third Year Geography and Management Student. Works in IT Support."
baseurl: ""
url: "http://tmault.co.uk"
google_analytics:
animated: false
show_related_posts: false

# Build settings
markdown: kramdown
permalink: pretty
paginate: 3
sass:
  compressed: true